name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Prisma generate
        working-directory: server
        env:
          DATABASE_URL: "file:./ci.db"
          DATABASE_PROVIDER: sqlite
        run: npm run generate

      - name: Prisma migrate deploy
        working-directory: server
        env:
          DATABASE_URL: "file:./ci.db"
          DATABASE_PROVIDER: sqlite
        run: npx prisma migrate deploy

      - name: Build server
        working-directory: server
        env:
          DATABASE_URL: "file:./ci.db"
          DATABASE_PROVIDER: sqlite
        run: npm run build

      - name: Seed database
        working-directory: server
        env:
          DATABASE_URL: "file:./ci.db"
          DATABASE_PROVIDER: sqlite
        run: npm run seed

      - name: API smoke test
        working-directory: server
        env:
          DATABASE_URL: "file:./ci.db"
          DATABASE_PROVIDER: sqlite
          PORT: "4000"
          ENABLE_CORS: "false"
        run: |
          node dist/index.js &
          SERVER_PID=$!
          sleep 5
          curl -f http://localhost:4000/api/employees || (kill $SERVER_PID && exit 1)
          kill $SERVER_PID
